
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: ebanking-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak-theme/capitalis:/opt/keycloak/themes/capitalis:ro

  auth-service:
    build: ./auth-service
    container_name: ebanking-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/ebanking-realm/protocol/openid-connect/certs
    depends_on:
      - keycloak

  postgres:
    image: postgres:15
    container_name: ebanking-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nouveaumdp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  user-service:
    build: ./user-service
    container_name: ebanking-user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nouveaumdp
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/ebanking-realm/protocol/openid-connect/certs
    depends_on:
      - keycloak
      - postgres

  gateway-service:
    build: ./gateway-service
    container_name: ebanking-gateway-service
    ports:
      - "4000:4000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - USER_SERVICE_URL=http://user-service:8082
    depends_on:
      - auth-service
      - user-service

volumes:
  postgres_data:
